# Generated by Django 5.1.7 on 2025-04-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AITS_USERS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second')], null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
